from multiprocessing import cpu_count

import streamlit as st

from artifact_ui.components.running_state import (disable_if_job_running,
                                                  launch_job)
from artifact_ui.components.time_estimator import (estimate_scene_generation,
                                                   format_duration)
from utils.artifact_config import ArtifactConfig
from utils.evaluation_config import (APPROACH_COMPARED_IN,
                                     APPROACH_DESCRIPTIONS, APPROACH_LABELS,
                                     MSR_CDRS_PS, PAPER_APPROACH_OPTIONS,
                                     UNBOUNDED_APPROACHES)

st.title("Scene Generation")

config = ArtifactConfig.from_env()
config.ensure_dirs()

st.markdown("""
Initial scenes are generated by **constraint satisfaction** over COLREGS scenarios.
Two generation workflows are compared in the paper:

- **Base**: uses logical-level scenario specifications directly.
- **MSR**: uses functional models (FSMs) from Refinery; required for CDRS/CDRS+PS variants.

Each pickable configuration below matches one row of *Table: Configurations of compared approaches*
in the paper.
""")

minimal_label = APPROACH_LABELS[MSR_CDRS_PS]
st.caption(
    f"**Kick-the-tires minimal run:** {minimal_label}, **2 vessels**, "
    "**1 seed**, **1 core** (defaults below)."
)

with st.expander("Compared approach configurations (paper Table)", expanded=False):
    for approach_id in PAPER_APPROACH_OPTIONS:
        compared = APPROACH_COMPARED_IN.get(approach_id, "")
        st.markdown(
            f"**{APPROACH_LABELS[approach_id]}**  \n"
            f"{APPROACH_DESCRIPTIONS[approach_id]}  \n"
            f"*Compared in:* {compared}"
        )

approaches = st.multiselect(
    "Approaches",
    options=PAPER_APPROACH_OPTIONS,
    default=[MSR_CDRS_PS],
    format_func=lambda key: APPROACH_LABELS.get(key, key),
    help="Configurations from the paper evaluation are selectable.",
)

vessel_counts = st.multiselect("Vessel counts", options=[2, 3, 4, 5, 6], default=[2])
st.text_input("Obstacle count", value="0 (fixed)", disabled=True)

st.markdown("""
**Random seeds**: Each seed repeats the full measurement batch with a different
pseudo-random initialization (`random_seed = base_seed + seed_index`). Multiple seeds
provide **statistical significance**: they capture variability in stochastic search and
sampling, so reported metrics (coverage, runtime, risk) reflect distribution across runs
rather than a single lucky or unlucky draw. The paper uses 30 seeds per configuration;
use fewer for kick-the-tires exploration.
""")
num_seeds = st.number_input(
    "Number of random seeds",
    min_value=1,
    max_value=100,
    value=1,
    help="Repeat the selected approach × vessel-count jobs this many times with different seeds.",
)

max_cores = st.slider("Max CPU cores", min_value=1, max_value=cpu_count(), value=1)

verbose = st.checkbox(
    "Verbose logging",
    value=False,
    help=(
        "When enabled, the job log includes per-scenario FEC progress, warmup status, "
        "and solver diagnostics. Leave off for quieter runs."
    ),
)

estimate = estimate_scene_generation(approaches, vessel_counts, num_seeds, max_cores)
st.info(
    f"Worst case: **{format_duration(estimate.worst_case_seconds)}** | "
    f"Typical: **{format_duration(estimate.typical_seconds)}**"
)
if estimate.warning:
    st.warning(estimate.warning)
if any(approach in UNBOUNDED_APPROACHES for approach in approaches):
    st.warning("Rejection-sampling approaches may run without a global timeout.")

st.caption(
    "When the job finishes, use **Download results** below to save a zip archive "
    "to your computer."
)

if st.button("Run scene generation", disabled=disable_if_job_running()):
    launch_job(
        "evaluation_main",
        {
            "approaches": approaches,
            "vessel_counts": vessel_counts,
            "obstacle_count": 0,
            "num_seeds": int(num_seeds),
            "max_cores": int(max_cores),
            "verbose": verbose,
        },
    )
